// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using NorthwindReversedPowerTools.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace NorthwindReversedPowerTools.Context
{
    public partial interface INorthwindContextProcedures
    {
        Task<List<GetTopIDsResult>> GetTopIDsAsync(int? top, OutputParameter<int?> overallcount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
