// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using NorthwindReversedPowerTools.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace NorthwindReversedPowerTools.Context
{
    public partial class NorthwindContext
    {
        private INorthwindContextProcedures _procedures;

        public virtual INorthwindContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new NorthwindContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public INorthwindContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetTopIDsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class NorthwindContextProcedures : INorthwindContextProcedures
    {
        private readonly NorthwindContext _context;

        public NorthwindContextProcedures(NorthwindContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetTopIDsResult>> GetTopIDsAsync(int? top, OutputParameter<int?> overallcount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameteroverallcount = new SqlParameter
            {
                ParameterName = "overallcount",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = overallcount?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "top",
                    Value = top ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameteroverallcount,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetTopIDsResult>("EXEC @returnValue = [dbo].[GetTopIDs] @top, @overallcount OUTPUT", sqlParameters, cancellationToken);

            overallcount.SetValue(parameteroverallcount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
